name = "angren-imi-news-worker"
main = "worker.js"
compatibility_date = "2024-06-30"

# D1 Database Binding
[[d1_databases]]
binding = "DB"
database_name = "angren-im"
database_id = "42a4736d-7ebd-46fc-bebd-721676786f1c"

# Environment variables
[vars]
ALLOWED_ORIGIN = "https://angren-im.uz"
